title: Probit and Logit Regression
description: [Home]("https://prakhosha.github.io/)
theme: minima

author:
  name: Angga Bayu Prakhosha
#  email: anggaprakhosha@gmail.com

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/prakhosha" }